accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/', views.delete_view, name='delete'),
    path('verify_email/<str:token>/', views.verify_email_view, name='verify_email'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from fox import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('fox.urls')),
    path('accounts/', include('accounts.urls')),
    
    #Password_Change
    path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    #Password_Reset
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

fox/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload_file, name='upload_file'),
    path('update/', views.filter_data, name='filter_data'),
    path('preview/', views.preview_report, name='preview_report'),
    path('community_report/', views.community_report, name='community_report'),
    path('school_zone/', views.school_zone, name='school_zone'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    is_email_verified = models.BooleanField(default=False)
    email_verification_token = models.CharField(max_length=200, blank=True, null=True)
    
    # Additional fields
    company_header = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    site_code = models.CharField(max_length=100, blank=True, null=True)
    report_description = models.TextField(blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import CustomUser
from django import forms


class RegistrationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username','email', 'password1','password2']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout, login, authenticate
from .forms import RegistrationForm
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
import uuid
from django.core.mail import send_mail
from .models import CustomUser
from django.http import HttpResponse

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_email_verified = False
            user.email_verification_token = str(uuid.uuid4())
            user.save()

            current_site = get_current_site(request)
            subject = "Activate your Account"
            activation_link = f"http://{current_site}/accounts/verify_email/{user.email_verification_token}/"
            message = f'Click the link to activate your account: {activation_link}'

            try:
                send_mail(subject,message,'awais_mazahir@hotmail.com',[user.email])
            except:
                pass
            
            return redirect ('accounts:login')
    else:
        form = RegistrationForm()
    
    return render (request, 'accounts/register.html', {'form':form})

def verify_email_view(request, token):
    try:
        user = CustomUser.objects.get(email_verification_token=token)
        if user:
            user.is_email_verified= True
            user.email_verification_token = None
            user.save()
            return redirect ('accounts:login')

    except:
        return redirect ('accounts:login')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():

            user = form.get_user()

            if user.is_email_verified:
                login (request, user)
                return redirect ('index')
    
            else:
                # messages.error(request, "Please Verify your Email")
                # return redirect ('accounts:login')
                login (request, user)
                return redirect ('index')
    else:
        form = AuthenticationForm()
    
    return render (request, 'accounts/login.html', {'form':form})

def logout_view(request):
    logout (request)
    return redirect ('accounts:login')

def delete_view(request):
    request.user.delete()
    messages.success(request, 'Your Account has been deleted Successfully')
    return redirect ('accounts:login')

accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Load Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet">

    <title>FOX Reporting</title>
</head>
<body>
    {% include 'accounts/header.html' %}

    <p></p>
    
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    {% include 'accounts/footer.html' %}
    
    <!-- Load Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

accounts/templates/accounts/footer.html
<!-- templates/footer.html -->

<footer class="footer bg-dark mt-5 fixed-bottom">
    <div class="container">
      <span class="text-muted text-center d-block">© 2024 FOX Reporting</span>
    </div>
  </footer>
  

accounts/templates/accounts/header.html
<!-- templates/header.html -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
      <img src="{% static 'accounts/img/logo.png' %}" alt="FOX Reporting Logo" height="30">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
      </li>
    </ul>
  </div>
</nav>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block content %}


<h1>Account Login</h1>
    <form method="post">

        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        {{ form|crispy  }}

        <button type="submit" class="btn btn-primary">Login</button>
    </form>


    <a href="{% url 'password_reset' %}">Forgot Password?</a>

    <p>Do not have an Account?</p>
    <a href="{% url 'accounts:register' %}">Register Here</a>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
    main {
        margin-bottom: 40px;
    }
</style>

<h1>Register your Account</h1>
    <form method="post">

        {% csrf_token %}
        {{ form|crispy  }}

        <button type="submit" class="btn btn-primary">Register</button>
    </form>

    <p>Already Registered?</p>
    <a href="{% url 'accounts:login' %}">Login Here</a>
{% endblock %}